version: '3.8'
services:
  mysql:
    image: mysql:latest  # 이미 로컬에 있는 MySQL 이미지 사용
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 계정 비밀번호
      MYSQL_DATABASE: movie   # 생성할 기본 데이터베이스
      MYSQL_USER: user  # 사용자 계정 (선택)
      MYSQL_PASSWORD: password  # 사용자 비밀번호 (선택)
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3305:3306"  # 호스트의 3305 포트를 컨테이너의 3306 포트와 연결