server:
  port: 8080

spring:
  application:
    name: movie
  datasource:
    url: jdbc:mysql://localhost:3305/movie?character_set_server=utf8mb4&connectionCollation=utf8mb4_unicode_ci
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      connection-timeout: 3000
      minimum-idle: 2
      idle-timeout: 0
      max-lifetime: 170000
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  sql:
    init:
      mode: always
      platform: mysql
      data-locations: classpath:data.sql
      separator: ';'